<div style="
    background: linear-gradient(90deg,#70c0c0,#40a8a8,#109090,#0a7070,#044848);
    font-family:'JetBrains Mono','Fira Code','Consolas',monospace;
    padding:8px 12px;
    border-radius:10px;
    text-align:center;
    color:#f2f0f7;
    box-shadow:0 4px 14px rgba(0,0,0,0.12);
">
    <h1 style="margin:0; font-size:20px; text-align:center; font-weight:700;">
        📱 Laptops Price Analysis
    </h1>
        Exploratory Data Analysis
</div>

<div style="
    background:#109090;
    font-family:'JetBrains Mono','Fira Code','Consolas',monospace;
    color:#f2f0f7;
    font-weight:600;
    padding:8px 12px;
    border-left:6px solid #70c0c0;
    border-radius:6px;
    box-shadow:0 4px 14px rgba(0,0,0,0.12);
    margin-top:4px;
">
    <h1 style="margin:0; font-size:16px; text-align:left; font-weight:700;">
        📚 Library Setup & Initialization
    </h1>
</div>

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio

import warnings

warnings.filterwarnings('ignore')
pio.renderers.default = 'iframe'
sns.set(style='darkgrid')
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter('ignore')

<div style="
    background:#109090;
    font-family:'JetBrains Mono','Fira Code','Consolas',monospace;
    color:#f2f0f7;
    font-weight:600;
    padding:8px 12px;
    border-left:6px solid #70c0c0;
    border-radius:6px;
    box-shadow:0 4px 14px rgba(0,0,0,0.12);
    margin-top:4px;
">
    <h1 style="margin:0; font-size:16px; text-align:left; font-weight:700;">
        🗂️ Load & Initialize Dataset
    </h1>
</div>

In [ ]:
df = pd.read_csv("../data/processed/laptops_cleaned.csv")
pd.set_option("display.max_columns", None)

<div style="
    background:#109090;
    font-family:'JetBrains Mono','Fira Code','Consolas',monospace;
    color:#f2f0f7;
    font-weight:600;
    padding:8px 12px;
    border-left:6px solid #70c0c0;
    border-radius:6px;
    box-shadow:0 4px 14px rgba(0,0,0,0.12);
    margin-top:4px;
">
    <h1 style="margin:0; font-size:16px; text-align:left; font-weight:700;">
        🧱 Structural & Integrity Checks 
    </h1>
</div>

In [3]:
df.head()

,brand,model,device_category,price,rating,cpu_brand,cpu_family,cpu_series,cpu_model,cpu_suffix,cpu_core_count,cpu_thread_count,cpu_p_cores,cpu_e_cores,cpu_lp_e_cores,ram_gb,storage_gb,display_width_px,display_height_px,display_size_inch,gpu_brand,gpu_series,gpu_model,gpu_vram_gb,gpu_type,os_name,warranty_years
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming,Gaming,189990,84,Intel,Core Ultra,Core Ultra 7,255HX,HX,20,20,8.0,12.0,NaN,32,1024,2560,1600,16,NVIDIA,GeForce RTX,RTX 5060,8.0,Dedicated,Windows,1
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN,Thin & Light,62350,54,Intel,Core,Core I5,13420H,H,8,12,4.0,4.0,NaN,16,1024,1920,1080,15,Intel,UHD,UHD Graphics,NaN,Integrated,Windows,1
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS,Thin & Light,34990,51,AMD,Ryzen,Ryzen 3,7320U,U,4,8,NaN,NaN,NaN,16,512,1920,1080,15,AMD,Radeon,Radeon,NaN,Integrated,Windows,1
3,lenovo,Lenovo V14 G3 82TS00JGUS,General,56990,48,Intel,Core,Core I7,1255U,U,10,12,2.0,8.0,NaN,16,512,1920,1080,14,Intel,Iris Xe,Iris Xe Graphics,NaN,Integrated,Windows,1
4,dell,Dell DC 14250 ODC1425000401RINS1,General,69990,52,Intel,Core,Core 5,120U,U,10,12,2.0,8.0,NaN,16,512,1920,1080,14,Intel,UHD,UHD Graphics,NaN,Integrated,Windows,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              992 non-null    object
 1   model              992 non-null    object
 2   device_category    992 non-null    object
 3   price              992 non-null    int64
 4   rating             992 non-null    int64
 5   cpu_brand          992 non-null    object
 6   cpu_family         992 non-null    object
 7   cpu_series         992 non-null    object
 8   cpu_model          992 non-null    object
 9   cpu_suffix         861 non-null    object
 10  cpu_core_count     992 non-null    int64
 11  cpu_thread_count   992 non-null    int64
 12  cpu_p_cores        703 non-null    float64
 13  cpu_e_cores        681 non-null    float64
 14  cpu_lp_e_cores     166 non-null    float64
 15  ram_gb             992 non-null    int64
 16  storage_gb         992 non-null    int64
 17  display_width_px   992 non-null    int64
 18  display_height_px  992 non-null    int64
 19  display_size_inch  992 non-null    int64
 20  gpu_brand          984 non-null    object
 21  gpu_series         984 non-null    object
 22  gpu_model          984 non-null    object
 23  gpu_vram_gb        292 non-null    float64
 24  gpu_type           984 non-null    object
 25  os_name            992 non-null    object
 26  warranty_years     992 non-null    int64
dtypes: float64(4), int64(10), object(13)
memory usage: 209.4+ KB

In [5]:
df.describe().round(2)

,price,rating,cpu_core_count,cpu_thread_count,cpu_p_cores,cpu_e_cores,cpu_lp_e_cores,ram_gb,storage_gb,display_width_px,display_height_px,display_size_inch,gpu_vram_gb,warranty_years
count,992.00,992.00,992.00,992.00,703.00,681.00,166.00,992.00,992.00,992.00,992.00,992.00,292.00,992.00
mean,87741.27,59.92,9.58,13.36,4.05,6.43,1.99,16.62,678.06,2047.36,1215.15,14.80,7.02,1.09
std,68578.31,11.67,4.49,5.62,2.14,3.02,1.04,7.52,382.16,385.40,275.57,0.89,3.54,0.33
min,12490.00,27.00,2.00,2.00,0.00,0.00,0.00,4.00,64.00,1080.00,720.00,11.00,2.00,1.00
25%,45912.50,52.00,6.00,10.00,2.00,4.00,2.00,16.00,512.00,1920.00,1080.00,14.00,4.00,1.00
50%,67990.00,59.00,8.00,12.00,4.00,6.00,2.00,16.00,512.00,1920.00,1080.00,15.00,6.00,1.00
75%,99240.00,66.00,10.00,16.00,6.00,8.00,2.00,16.00,1024.00,1920.00,1200.00,15.00,8.00,1.00
max,605990.00,98.00,24.00,32.00,10.00,16.00,4.00,64.00,6144.00,3840.00,2400.00,18.00,24.00,3.00

In [6]:
df.isnull().sum()

brand                  0
model                  0
device_category        0
price                  0
rating                 0
cpu_brand              0
cpu_family             0
cpu_series             0
cpu_model              0
cpu_suffix           131
cpu_core_count         0
cpu_thread_count       0
cpu_p_cores          289
cpu_e_cores          311
cpu_lp_e_cores       826
ram_gb                 0
storage_gb             0
display_width_px       0
display_height_px      0
display_size_inch      0
gpu_brand              8
gpu_series             8
gpu_model              8
gpu_vram_gb          700
gpu_type               8
os_name                0
warranty_years         0
dtype: int64

In [7]:
print("Duplicated Rows:",df.duplicated().sum())
print("-"*30)
print("Number of Rows:",df.shape[0])
print("-"*30)
print("Number of Columns:",df.shape[1])

Duplicated Rows: 0
------------------------------
Number of Rows: 992
------------------------------
Number of Columns: 27

<div style="
    background:#109090;
    font-family:'JetBrains Mono','Fira Code','Consolas',monospace;
    color:#f2f0f7;
    font-weight:600;
    padding:8px 12px;
    border-left:6px solid #70c0c0;
    border-radius:6px;
    box-shadow:0 4px 14px rgba(0,0,0,0.12);
    margin-top:4px;
">
    <h1 style="margin:0; font-size:16px; text-align:left; font-weight:700;">
        🗂️ Univariate Analysis
    </h1>
</div>

# The univariate analysis will be ready by end of day tomorrow.